# the pipeline is to have the raw data here and clean it
# then move it to cleaned config
# the rAW data are from the notebooks cleaning_Preproceeesing folder
rawdatapath:
    TrainDir: Dataset/trainData/
    trainDatasetName: meterOneTrainData.csv
    trainDatasetName2: meterZeroTrainData.feather
    

cleanedtest:
      TargetDir: Dataset/testData/
      testDatasetName: testZero.csv
      testFeatureSet: testZero.feather
      testData : testZeroData.csv
      LSTMtestFeatureSet: lstmtestZero.npy

# the first version is cleanedDataV1. If a new cleaned data is entered then a 
# new documentation should be entered here 
cleanedconfig:
    cleanedDataV1 : 
        version: V1
        cleanedDir: Dataset/trainData/cleaned/
        cleanedName: cleanedDataV1.csv
        metadata : 'For meter1. zeros have been  removed from the data set. Forward filling for air and dew temperature.'
        datasize: 4182440
        NumberOfZerosMeterReadings: 656504
        datasizeNonZeros: 3525936
        FeatureSize: 32 
        trainFeatureSize: 31
        targetfeatureSize: 1
        targetName : 'meter_reading'
        validationSplit: 1000
        TensorflowDataFlowConfig:
            tfprocess: True
            tfcleanTrain: tftrains.csv
            tfcleanValidate: tfvals.csv
            NumberOfCategoricalFeatures: 3
            categoricalFeatureToUse: 3
            CategoricalFeature:
                                - 'month_day_hour'
                                - 'primary_use'
                                - 'site_id'
    cleanedDataV2 : 
        version: V2
        cleanedDir: Dataset/trainData/cleaned/
        cleanedName: cleanedDataV2.feather
        metadata : 'For meter 0 (elecricity). zeros have been  removed from the data set. Forward filling for air and dew temperature.'
        datasize: 12060910
        NumberOfZerosMeterReadings: 530169
        datasizeNonZeros: 11530741
        FeatureSize: 40 
        trainFeatureSize: 39
        targetfeatureSize: 1
        targetName : 'meter_reading'
        validationSplit: 2000
        TensorflowDataFlowConfig:
            tfprocess: True
            tfcleanTrain: tftrainZero.csv
            tfcleanValidate: tfvalsZero.csv
            NumberOfCategoricalFeatures: 3
            categoricalFeatureToUse: 3
            CategoricalFeature:
                                - 'month_day_hour'
                                - 'primary_use'
                                - 'site_id'

# each person can create a new id to save their model. Change myname. 
savedModel:
   myname:
         modelName: tfAPIKeras.ckpt
         Dir: savedModels/tfAPIKeras/
         Dir2: savedModels/tfAPINormalized/
         modelName2 : tfAPINormalized.ckpt
         Dir3: savedModels/CombinedLinear/
         Dir4: savedModels/lightgbm/
         modelName4 : lightgbm.txt
         Dir5: savedModels/lstmModel/
         modelName5 : lstmModel.ckpt
   myname2:
         modelName: tfAPIKeras.ckpt
         Dir: savedModels/tfAPIKeras2/
         Dir2: savedModels/tfAPINormalized2/
         modelName2 : tfAPINormalized.ckpt
         Dir3: savedModels/CombinedLinear2/
         Dir4: savedModels/lightgbm2/
         modelName4 : lightgbm.txt
         Dir5: savedModels/lstmModel2/
         modelName5 : lstmModel.ckpt
         